spring.profiles.active: dev

---
spring.profiles: dev
spring.profiles.include:
  - default
  - development

---
spring.profiles: prod
spring.profiles.include:
  - default
  - production

---
spring.profiles: default

spring.h2.console:
  enabled: true
  path: /h2

spring.datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:file:./.h2/demo
  username: sa
  password:

spring.jpa.hibernate.ddl-auto: update

server:
  port: 80
  logging.level.web: debug

---
spring.profiles: development
# ORM logging with Hibernate
#logging.level.org.hibernate:
#    SQL: debug
#    type.descriptor.sql: trace

# ORM logging with Spring Data JPA
spring.jpa.show-sql: true
#spring.jpa.properties.hibernate.format_sql=true

---
spring.profiles: production